// GENERATED by scripts/import-last-click-city.ts — do not edit by hand.
// Category membership + pillar (index) ordering recovered from the old blog.

export type ArchiveCategory = { slug: string; title: string; articleSlugs: string[] };

export const CATEGORIES: ArchiveCategory[] = [
  {
    "slug": "attribution-models",
    "title": "Attribution Models",
    "articleSlugs": [
      "markov-chain-attribution-model",
      "the-shapley-value-in-data-driven-attribution"
    ]
  },
  {
    "slug": "google-analytics",
    "title": "Google Analytics",
    "articleSlugs": [
      "advertising-features-google-analytics-proper-use",
      "every-single-reason-why-a-google-analytics-session-will-start-over",
      "myths-about-bounce-rate",
      "reverse-page-path-in-google-bigquery",
      "five-reasons-why-you-should-use-bigquery-for-your-google-analytics-data",
      "google-analytics-user-based-events-funnel-in-bigquery",
      "enhanced-link-attribution",
      "custom-dimensions-in-google-analytics",
      "campaign-timeout-ga-setting-that-matters",
      "pulling-out-the-next-page-visited-by-new-users-in-google-bigquery",
      "full-referrer-dimension-assisted-revenue",
      "calculating-audience-intersection-in-google-bigquery",
      "top-conversion-paths-in-ga-and-bigquery",
      "custom-event-trigger-in-google-tag-manager",
      "assisted-conversions-report-bigquery",
      "mcf-acquisition-reports-difference-in-conversion-data"
    ]
  },
  {
    "slug": "google-bigquery",
    "title": "Google BigQuery",
    "articleSlugs": [
      "simple-attributions-via-sql-in-bigquery",
      "reverse-page-path-in-google-bigquery",
      "five-reasons-why-you-should-use-bigquery-for-your-google-analytics-data",
      "google-analytics-user-based-events-funnel-in-bigquery",
      "how-to-work-in-google-bigquery-using-sql",
      "bigquery-user-defined-functions",
      "bigquery-interface-overview",
      "pulling-out-the-next-page-visited-by-new-users-in-google-bigquery",
      "bigquery-totals-by-day-totals-by-data-range",
      "update-tables-using-views-and-Google-Apps-Scripts",
      "full-referrer-dimension-assisted-revenue",
      "calculating-audience-intersection-in-google-bigquery",
      "top-conversion-paths-in-ga-and-bigquery",
      "assisted-conversions-report-bigquery",
      "mcf-acquisition-reports-difference-in-conversion-data"
    ]
  },
  {
    "slug": "google-tag-manager",
    "title": "Google Tag Manager",
    "articleSlugs": [
      "gtm-events-proper-usage",
      "custom-event-trigger-in-google-tag-manager"
    ]
  }
];

export const PILLAR_ORDER: string[] = [
  "user-journey-and-multi-channel-funnel-using-appsflyer-data",
  "six-differences-between-a-session-in-ga4-and-a-session-in-ua",
  "how-to-set-up-events-in-google-analytics-4-correctly",
  "watch-the-trap-unique-events-in-google-analytics",
  "the-future-of-digital-analytics-and-advertising-in-a-world-without-third-party-cookies",
  "unnest-key-value-data-relating-to-objects-in-different-columns",
  "get-the-value-of-utm-parameters-using-sql",
  "marketing-budget-allocation-via-linear-programming",
  "checking-events-firing-android-firebasega4",
  "advertising-features-google-analytics-proper-use",
  "comparative-measurement-methods-of-global-changes-for-marketers",
  "every-single-reason-why-a-google-analytics-session-will-start-over",
  "myths-about-bounce-rate",
  "requirements-and-rules-of-application-promotion-via-google-ads",
  "prediction-of-campaign-results-using-python",
  "simple-attributions-via-sql-in-bigquery",
  "youtube-brand-lift-study",
  "reverse-page-path-in-google-bigquery",
  "five-reasons-why-you-should-use-bigquery-for-your-google-analytics-data",
  "google-analytics-user-based-events-funnel-in-bigquery",
  "markov-chain-attribution-model",
  "enhanced-link-attribution",
  "how-to-work-in-google-bigquery-using-sql",
  "bigquery-user-defined-functions",
  "custom-dimensions-in-google-analytics",
  "reasons-why-your-digital-marketing-campaign-may-fail",
  "yandex-direct-starter-pack",
  "the-shapley-value-in-data-driven-attribution",
  "gtm-events-proper-usage",
  "campaign-timeout-ga-setting-that-matters",
  "bigquery-interface-overview",
  "pulling-out-the-next-page-visited-by-new-users-in-google-bigquery",
  "bigquery-totals-by-day-totals-by-data-range",
  "update-tables-using-views-and-Google-Apps-Scripts",
  "full-referrer-dimension-assisted-revenue",
  "calculating-audience-intersection-in-google-bigquery",
  "top-conversion-paths-in-ga-and-bigquery",
  "custom-event-trigger-in-google-tag-manager",
  "assisted-conversions-report-bigquery",
  "mcf-acquisition-reports-difference-in-conversion-data"
];
